/* 
 * Purpose: forwards the calls to the original dll
 */

// Took from SO
// https://stackoverflow.com/questions/39688983/mingw-forward-dll-call
// Apparently it is realted to a tool called 'dlltool' which is not always present according to the gnu docs

#ifdef _MSC_VER
    #define FORWARDED_EXPORT_WITH_ORDINAL(exp_name, ordinal, target_name) __pragma (comment (linker, "/export:" #exp_name "=" #target_name ",@" #ordinal))
#endif
#ifdef __GNUC__
    #define FORWARDED_EXPORT_WITH_ORDINAL(exp_name, ordinal, target_name) __asm__(".section .drectve\n\t.ascii \" -export:" #exp_name "= " #target_name " @" #ordinal "\"");
#endif

FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferBlit@12,1,binkw32_._BinkBufferBlit@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferCheckWinPos@12,2,binkw32_._BinkBufferCheckWinPos@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferClear@8,3,binkw32_._BinkBufferClear@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferClose@4,4,binkw32_._BinkBufferClose@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferGetDescription@4,5,binkw32_._BinkBufferGetDescription@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferGetError@0,6,binkw32_._BinkBufferGetError@0)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferLock@4,7,binkw32_._BinkBufferLock@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferOpen@16,8,binkw32_._BinkBufferOpen@16)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetDirectDraw@8,9,binkw32_._BinkBufferSetDirectDraw@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetHWND@8,10,binkw32_._BinkBufferSetHWND@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetOffset@12,11,binkw32_._BinkBufferSetOffset@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetResolution@12,12,binkw32_._BinkBufferSetResolution@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferSetScale@12,13,binkw32_._BinkBufferSetScale@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkBufferUnlock@4,14,binkw32_._BinkBufferUnlock@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCheckCursor@20,15,binkw32_._BinkCheckCursor@20)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkClose@4,16,binkw32_._BinkClose@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCloseTrack@4,17,binkw32_._BinkCloseTrack@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkCopyToBuffer@28,18,binkw32_._BinkCopyToBuffer@28)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDDSurfaceType@4,19,binkw32_._BinkDDSurfaceType@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDX8SurfaceType@4,20,binkw32_._BinkDX8SurfaceType@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkDoFrame@4,21,binkw32_._BinkDoFrame@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetError@0,22,binkw32_._BinkGetError@0)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetKeyFrame@12,23,binkw32_._BinkGetKeyFrame@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetRealtime@12,24,binkw32_._BinkGetRealtime@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetRects@8,25,binkw32_._BinkGetRects@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetSummary@8,26,binkw32_._BinkGetSummary@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackData@8,27,binkw32_._BinkGetTrackData@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackID@8,28,binkw32_._BinkGetTrackID@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackMaxSize@8,29,binkw32_._BinkGetTrackMaxSize@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGetTrackType@8,30,binkw32_._BinkGetTrackType@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkGoto@12,31,binkw32_._BinkGoto@12)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkIsSoftwareCursor@8,32,binkw32_._BinkIsSoftwareCursor@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkLogoAddress@0,33,binkw32_._BinkLogoAddress@0)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkNextFrame@4,34,binkw32_._BinkNextFrame@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpen@8,35,binkw32_._BinkOpen@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenDirectSound@4,36,binkw32_._BinkOpenDirectSound@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenMiles@4,37,binkw32_._BinkOpenMiles@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenTrack@8,38,binkw32_._BinkOpenTrack@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkOpenWaveOut@4,39,binkw32_._BinkOpenWaveOut@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkPause@8,40,binkw32_._BinkPause@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkRestoreCursor@4,41,binkw32_._BinkRestoreCursor@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkService@4,42,binkw32_._BinkService@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetError@4,43,binkw32_._BinkSetError@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetFrameRate@8,44,binkw32_._BinkSetFrameRate@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetIO@4,45,binkw32_._BinkSetIO@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetIOSize@4,46,binkw32_._BinkSetIOSize@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetPan@8,47,binkw32_._BinkSetPan@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSimulate@4,48,binkw32_._BinkSetSimulate@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSoundOnOff@8,49,binkw32_._BinkSetSoundOnOff@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSoundSystem@8,50,binkw32_._BinkSetSoundSystem@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetSoundTrack@4,51,binkw32_._BinkSetSoundTrack@4)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetVideoOnOff@8,52,binkw32_._BinkSetVideoOnOff@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkSetVolume@8,53,binkw32_._BinkSetVolume@8)
FORWARDED_EXPORT_WITH_ORDINAL(_BinkWait@4,54,binkw32_._BinkWait@4)
FORWARDED_EXPORT_WITH_ORDINAL(_RADTimerRead@0,55,binkw32_._RADTimerRead@0)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_16a1bpp@52,56,binkw32_._YUV_blit_16a1bpp@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_16a1bpp_mask@52,57,binkw32_._YUV_blit_16a1bpp_mask@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_16a4bpp@52,58,binkw32_._YUV_blit_16a4bpp@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_16a4bpp_mask@52,59,binkw32_._YUV_blit_16a4bpp_mask@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_16bpp@48,60,binkw32_._YUV_blit_16bpp@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_16bpp_mask@48,61,binkw32_._YUV_blit_16bpp_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_24bpp@48,62,binkw32_._YUV_blit_24bpp@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_24bpp_mask@48,63,binkw32_._YUV_blit_24bpp_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_24rbpp@48,64,binkw32_._YUV_blit_24rbpp@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_24rbpp_mask@48,65,binkw32_._YUV_blit_24rbpp_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32abpp@52,66,binkw32_._YUV_blit_32abpp@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32abpp_mask@52,67,binkw32_._YUV_blit_32abpp_mask@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32bpp@48,68,binkw32_._YUV_blit_32bpp@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32bpp_mask@48,69,binkw32_._YUV_blit_32bpp_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32rabpp@52,70,binkw32_._YUV_blit_32rabpp@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32rabpp_mask@52,71,binkw32_._YUV_blit_32rabpp_mask@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32rbpp@48,72,binkw32_._YUV_blit_32rbpp@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_32rbpp_mask@48,73,binkw32_._YUV_blit_32rbpp_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_UYVY@48,74,binkw32_._YUV_blit_UYVY@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_UYVY_mask@48,75,binkw32_._YUV_blit_UYVY_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_YUY2@48,76,binkw32_._YUV_blit_YUY2@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_YUY2_mask@48,77,binkw32_._YUV_blit_YUY2_mask@48)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_blit_YV12@52,78,binkw32_._YUV_blit_YV12@52)
FORWARDED_EXPORT_WITH_ORDINAL(_YUV_init@4,79,binkw32_._YUV_init@4)
FORWARDED_EXPORT_WITH_ORDINAL(_radfree@4,80,binkw32_._radfree@4)
FORWARDED_EXPORT_WITH_ORDINAL(_radmalloc@4,81,binkw32_._radmalloc@4)
