name: C/C++ CI

on:
  push:
    branches: [ "master", "windows_pipelines" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-i686-gcc
