name: C/C++ CI

on:
  push:
    branches: [ "master", "windows_pipelines" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-texture_loader:

    runs-on: windows-2022
    steps:
    - uses: ilammy/setup-nasm@v1.4.0
    - uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v3
    - name: Build texture loader
      working-directory: ./texture_loader
      run: |
        nasm hooks.s -f win -o hooks.obj
        msbuild /p:Platform=x86 /p:Configuration=Release
    - name: Prepare output
      run: |
        mkdir output
        cp texture_loader\Release\texture_loader output\binkw32.dll
        cp texture_loader\sm2000.json output\.
    - uses: actions/upload-artifact@v3
      with:
        path: output
        name: texture_loader
